#!/usr/bin/env python3
from importlib.machinery import SourceFileLoader
import os
import sys
import multiprocessing as mp
import click
from inspect import signature
import itertools as it
import more_itertools as mi
from pathlib import Path

sys.dont_write_bytecode = True

def load_from_file(filepath: Path):
    if filepath.suffix.lower() == '.py':
        return SourceFileLoader(filepath.stem, str(filepath)).load_module()
    else:
        raise Exception(f"can not load {filepath}")

class RunCmd:
    def __init__(self, cmd):
        self.cmd = cmd
        self.__doc__ = f"run shell command: {cmd}"

    def __call__(self, f):
        os.system(self.cmd.format(f=f))

def get_default_generator(input, splitby):
    input = it.chain.from_iterable(sys.stdin) if input == '-' else input
    def wrap():
        for x in mi.split_at(input, lambda x: x in splitby):
            x = ''.join(x).strip()
            if len(x) > 0:
                yield x
    return wrap()

@click.command(context_settings={"ignore_unknown_options":True},
        help="""Example:

`pypara -p example1.py`

\b
use ruuning function from example1.py with given generator
`pypara -p example1.py -g "1 2 3"`

\b
use generator from example1.py with given running command
`pypara -p example1.py -r "echo cmd{f}"`

\b
Pass argument to generator in example2.py
`pypara -p example2.py --run "echo cmd{f}" --count 3`

\b
With pipe
`echo "0 1 2" | pypara -g - --run "echo cmd{f}"`

\b
Change spliting character
`pypara -g "0_1_2" --run "echo cmd{f}" --splitby "_"`
""")
@click.option("--pkg", "-p", default=None, type=Path,
        help="path to a python file, which usually includes a variable/function for generator and a function to be called.")
@click.option("--run", "-r", default=None, type=str,
        help="shell command to be run, example: `'echo {f}'`")
@click.option("--nproc", "-n", type=int, default=mp.cpu_count(),
        help="number of processes for running command")
@click.option("--generator", "-g", default=None, help="")
@click.option("--splitby", default=" ", type=str,
        help="character used for splitting input string")
@click.option("--test", is_flag=True,
        help="Test mode, only run the first output from the generator")
@click.option("--subhelp", is_flag=True,
        help="get help doc from package")
@click.argument('params', nargs=-1, type=click.UNPROCESSED)
def cli(params, pkg: Path, nproc: int, test: bool, generator, run, splitby, subhelp):
    if pkg is not None:
        pkg = load_from_file(pkg)

    if subhelp:
        doc = getattr(pkg, "__doc__", None)
        if doc:
            print("=== Script help === ")
            print(doc)
        if isinstance(getattr(pkg, "generator", None), click.Command):
            print("=== Generator help === ")
            pkg.generator(['--help'], standalone_mode=False)
        else:
            if generator:
                print("=== Generator help === ")
                print(generator)

        if run:
            doc = run
        elif hasattr(pkg, "run"):
            doc = getattr(pkg.run, "__doc__")
        if doc:
            print("=== Run help === ")
            print(doc)
        return

    if generator is not None:
        generator = get_default_generator(generator, splitby)
    elif pkg is not None and hasattr(pkg, "generator"):
        if isinstance(pkg.generator, click.Command):
            generator = pkg.generator(params, standalone_mode=False)
        else:
            generator = pkg.generator
    else:
        raise Exception("Can not identify generator")

    if run is not None:
        run = RunCmd(run)
    elif pkg is not None and hasattr(pkg, "run"):
        run = pkg.run
    else:
        raise Exception("Can not identify run")

    star = len(signature(run).parameters.keys()) > 1
    if test:
        generator = [(next(iter(generator)))]
    pool = mp.Pool(nproc)
    if star:
        result = pool.starmap(run, generator)
    else:
        result = pool.map(run, generator)


if __name__ == "__main__":
    cli()
